{{- if eq (include "bitcoin.fullname" .) "bitcoin" }}
apiVersion: v1
kind: Secret
metadata:
  name: network
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
stringData:
  network: {{.Values.global.network}}
{{- end }}
