{{ $rpcpassword := include "rpcpassword" . }}
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rpcpassword" (include "bitcoin.fullname" .) }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
stringData:
  password: {{ $rpcpassword }}
{{- end }}
