apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitcoin-node
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudores/40acres-test-task.git
    targetRevision: master
    path: argocd/charts/bitcoind
    helm:
      values: |
        global:
          network: testnet
          service:
            ports:
              rpc: 8332
        bitcoinConfig: |
          server=1
          listen=1
          testnet=1
          prune=1000
          txindex=0
          rpcallowip=0.0.0.0/0
          whitelist=0.0.0.0/0
          listenonion=0
          rpcuser=bitcoin
          rpcpassword=bitcoin
          fallbackfee=0.00001
          blockfilterindex=1
          peerblockfilters=1
          rpcworkqueue=64
          [test]
          rpcport=8332
          rpcbind=0.0.0.0
          dns=1
        replicaCount: 1
        image:
          repository: ghcr.io/cosmicrocks/knots
          tag: "28.1.knots20250305"
          pullPolicy: Always

        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 2Gi
          storageClass: standard

        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi

        service:
          type: ClusterIP
          ports:
            zmqpubrawtx: 8431
            zmqpubrawblock: 8432
            zmqpubhashblock: 8433
            p2p: 8333
            rpc: 8332
            metrics: 9223

  destination:
    server: https://kubernetes.default.svc
    namespace: bitcoin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
