apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitcoin-node
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://cosmicrocks.github.io/helm-charts/
    chart: bitcoin
    targetRevision: 2.0.2
    helm:
      values: |
        global:
          network: testnet
          service:
            ports:
              rpc: 8332

        bitcoin:
          serverEnabled: 1
          txindexEnabled: 0
          printtoconsoleEnabled: 1
          rpcUser: bitcoin
          rpcBind: "0.0.0.0"
          rpcAllowIP: "0.0.0.0/0"
          dbCrashRatio: 0.0001
          listenonion: 0
          fallbackfee: 0.00001
          blockReconstructionExtraTxn: 10000
          blockfilterindex: 1
          peerblockfilters: 1
          rpcWorkQueue: 64
          test:
            rpcport: 8332
            rpcbind: "0.0.0.0"
            dns: 1

        replicaCount: 1

        image:
          repository: ghcr.io/cosmicrocks/knots
          tag: "28.1.knots20250305"
          pullPolicy: Always

        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 2Gi
          storageClass: standard

        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi

        service:
          type: ClusterIP
          ports:
            zmqpubrawtx: 8431
            zmqpubrawblock: 8432
            zmqpubhashblock: 8433
            p2p: 8333
            rpc: 8332
            metrics: 9223

  destination:
    server: https://kubernetes.default.svc
    namespace: bitcoin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
